name: scrape-news
on:
  schedule:
    - cron: "0 23 * * *"  # 18:00 Bogotá (UTC-5) = 23:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          
      - name: Run scraper
        run: |
          python scripts/scrape_news.py \
          --outdir data \
          --pages 3 \
          --max-per-factcheck 200 \
          --max-per-trusted 70 \
          --target-total 360 \
          --ratio "falso=0.4,verdadero=0.4,dudoso=0.2"
            
      - name: Consolidate history
        run: |
          python scripts/consolidate.py data data/dataset_historico.csv

      - name: Clean historical (mojibake + listados)
        run: |
          python scripts/clean_historico.py data/dataset_historico.csv data/dataset_historico_clean.csv  

      - name: Validate & report
        run: |
          python scripts/validate.py data data/reportes

      - name: Upload artifacts (jsonl/parquet/reportes)
        uses: actions/upload-artifact@v4
        with:
          name: datasets-${{ github.run_id }}
          path: |
            data/jsonl/*.jsonl
            data/parquet/*.parquet
            data/reportes/*.md

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily scrape + consolidate + report"
          file_pattern: |
            data/*.csv
            data/jsonl/*.jsonl
            data/parquet/*.parquet
            data/reportes/*.md
            data/html/**
            
